onecompiler/cheatsheets

cpp.md

stack and queue are the basic and crucial data structures ... i added their basic information...their basic operations and their exampler code which is very beneficial for our users and top coders.

added information about stack and queue

---

css.md
html.md

made a new file css.md . remove the some css content from html.md

created css.md file

---

html.md

add input type for number in input elements

Add input type - number

---

cpp.md
linux.md

Updated linux.d as well as cpp.md

update linux.md and cpp.md

---

css.md

added information about display property in css as before using flex box, CSS grids it is important to know more about display property

added display property

---

java-versions.md

Added new java versions

---

cpp.md

there was information about structures in c++ but there was no information about classes in c++ so i added basic information about classes and some sample code I hope it will be useful 😄
hacktoberfest 2022 😄❤

Added information about classes

---

python.md

I added about Try Except in Python.
Explain about how to use _try except_ block, in addition to use _finally_ and many exceptions.

Update python.md [Try Except]

---

html.md

Pre is one of the most important  andbasic tag to be used in HTML  so this PR adds its details in the documentation
Text in a pre element
is displayed in a fixed-width
font, and it preserves
both      spaces and
line breaks

Added Pre Tag in HTML tags

---

vuejs.md

VueJS cheatsheet

---

git.md

I have added `git rebase` command to squash multiple commits into one commit.
I have also added `git stash clear` commit
It solvs #42

Updated `GIT` cheetsheet

---

go.md

Added information about Generics which were introduced to Go in 1.18.

Updated go.md

---

solidity.md

Included a solidity cheat sheet markdown file with basic implementations, examples, and formats. This marks an issue raised and submitted earlier closed #49 
I hope it is your satisfaction. Appreciate the opportunity.

Added Solidity cheatsheet file

---

flutter.md

Added quick references of basic widgets, snippets and attributes of flutter.

Added Flutter Cheatsheet resources.

---

javascript.md

Javascirpt is incomplete without the information about DOM so I added an overview of javascript DOM in this cheatsheet which will be very beneficial
Hacktoberfest 2022❤

Added information about javaScript DOM

---

css.md

added variable to the CSS cheatsheet

---

java.md

Hashmap Hashset and arraylist are important collections in Java . So i think general information about Hashpmap , hashset and array list should be provided. So i added the basic information about these 
Hacktoberfest ❤

Updated Hashset Hashmap and Arrraylist

---

cpp.md

header file has been shifted to bottom
It is now stored in  a table

the changes are done

---

css.md

Added more power to the "CSS cheatsheet" selector section

---

iphone-screen-resolutions.md

Added latest iphone model's resolutions and corrected some old resolutions.

Updated iphone-screen-resolutions.md

---

css.md

I have added the topic Added Animations and Transitions.

Added Animations and Transitions

---

css.md

Added units to the CSS cheatsheet

---

sql.md

UPDATED SQL JOINS

---

css.md

Added Media queries section to the CSS cheatsheet

---

c.md

I have added various string functions and the topic Dynamic Memory Allocation.

Added string functions and Dynamic Memory Allocation

---

cpp.md

Adds information about bits/stdc++.h file that is used to add all files with a single file

Adds information about bits/stdc++.h file

---

php.md

I have added SQLi Functions in php.

Added MySQLi Functions

---

kubernetes.md

This is my PR to issue #94 as part of Hacktoberfest 2022. I've added a cheatsheet for Kubernetes covering all the major functionalities and commands. Could you please review my PR and merge it @onecompiler-ops

Added the Kubernetes cheat sheet as part of Hacktoberfest- Issue #94

---

linux.md

Updated the Linux cheat sheet with further breakdowns of tar and file permissions.

Updated Linux Cheatsheet

---

html.md

I have added audio and video tag in HTML Tag table

Added audio and video tag in HTML Tag table

---

python.md

The code was written for if-elif-else ladder but was titled as nested if else

Corrected the title in Conditional statements

---

javascript-versions.md

added JS 2019 details

---

cpp.md

Added some changes seemed necessary for cheatsheet.

 Added boolean Literal, graphics.h, greater function in sorting

---

cpp.md

Added more Bitwise Operators in cpp.md

Updated cpp.md

---

html.md

html-lazy-load-feature

---

jQuery.md

issue number #172 
Cheatsheet of Jquery was added. 
@onecompiler-ops Please merge this pull request under Hacktober 2022.

Added jQuery.md

---

c.md

Added Header files Information in c.md

---

cat.md
css.md

1. Have fixed the wrong numberings in some files which I found, as mentioned in issue #184 
2. Also, went through and proofread files for typos

(fix) wrong numberings in some files

---

java.md

Added 2 more types of comments in java.md at line no. 50

Updated  Java.md file

---

http-staus-codes.md

(new) HTTP status code cheatsheet

---

python.md

Added a brief concept of type casting in python.

Python datatype

---

java.md

Updated the brief note of Constructor and its syntax.

Constructor java

---

c.md

added left shift operator at line no. 153
Please merge it and let me know if any changes are needed Prateek Roy

Updated c.md

---

cpp.md

Some missing information about variable naming conventions has been added. Please review and  approve

Update  cpp.md in variable naming convention

---

c.md

A few string functions which were missing from the cheatsheet are added #272

Updated string functions of c.md

---

cpp.md

A ternary operator evaluates the test condition and executes a block of code based on the result of the condition. 
Short but very useful while programming.

Adding syntax of ternary operator in cpp.md

---

html.md

Adds Source Tag that Defines multiple media resources for media elements.

Adds Source Tag

---

html.md

Adds <big> tag that is used to increase the font size by one conventional unit.

Adds <big> tag

---

cpp.md

I have only mention those functions of string which are used almost in all string problems.
I have not mentioned other functions so that it doesn't become verbose.
If you want I can add them as well.

added String in cpp.md

---

c.md

I added the method through which we can read a line from input using scanf() only , i.e. without using the getline function
please add the labels hacktoberfest-2022 and hacktoberfest-accepted #30 
#36

Added a method in c.md

---

cpp.md

keywords (also known as reserved words)

Adding cpp keywords in cpp.md

---

cpp.md

bits/stdc++.h in header files is there twice so removed one.

Removes bits/stdc++.h from header files

---

html.md

Adds range in input which is a range slider control.

Adds range in input

---

html.md

Adds SVG element which is used to define vector-based graphics for the Web.

Adds SVG element

---

php.md

I have added Date function, some important file functions and mysqli extensions and fixed some wrongly written variable name.

Added Date, file, some mysqli extensions, superglobals and fixed some typos

---

my-sql.md

The cursor is an important topic, and every user of MySQL should know it.
Hence adding it.
I hope my little contribution with worth merging
Thank you

Adding cursor topic in mysql.md

---

csharp.md

Added a few missing string functions which were missing to csharp.md

Added string functions

---

html.md

Adds iframe tag that is used to It is used to specifies an inline frame.

Adds iframe tag

---

mysql.md

Changed name in the local repo and then updated the name and then committed changes

Updated triggers in mysql.md

---

cpp.md

I added another method by which we can sort the array in desc order using the reverse iterator , added how to sort only a part of the vector, and also updated the info about some headers

Added some methods in sorting and updated info of some headers

---

r.md

- I have added R language's matrix operations and apply functions
- I have given the proper syntax with each content
- I have followed the code style of the project.

Adding matrix operations and apply functions into 'r' cheatsheet

---

nodejs.md

Added a few changes and will be adding more changes later on. Please merge this under the Hacktoberfest label.

Update node cheat sheet

---

html.md

Adds Progress tag that represents the completion progress of a task.

Adds Progress Tag

---

html.md

Adds Kbd tag ie keyboard input tag

Adds Kbd Tag

---

css.md

Few relative units were missing from the cheat sheet which have been updated

Updated missing relative units in css.md

---

java.md

Stack which is an essential part of DSA was missing in collection of java.md and has been added now.

Updated collections in java.md

---

c.md

Added 2 missing functions in string domain in c.md

Updated string functions in c.md

---

java.md

naming convention about variables and class_name was incomplete and some information about naming convention was missing which has been added please review and approve

Update java.md for minor changes

---

mysql.md

documentation for sql commands was insufficient which has been added
please review and approve

Documentation for various sql commands in Mysql.md

---

Azure_Fundamentals.md

 Azure Cheatsheet

---

cpp.md

I added a few more functions under the vector section in the C++ cheatsheet. They are functions which a user would be needing frequently if they are working with vectors. I request you to please look through my pull request and merge it if there are no issues. Please feel free to contact me if something needs to be added, deleted or edited.

Adding some useful vector functions in C++ cheatsheet

---

c.md

Added strstr() function details which was missing in c.md string functions

Updated missing string function in c.md

---

cpp.md

Some header files were not listed in cpp.md that have been added

Updated cpp.md with missing header files

---

cpp.md

I added the References in cheatsheets -cpp.md , take a look .

added-references-cpp.md

---

html.md

Adds bdo tag that is bidirectional override text .

Adds <bdo> tag

---

html.md

Added missing input tag for taking image as an input in html.md

Updated a missing input tag from html.md

---

cpp.md

I have added 2 more escape sequences to the already existing cpp file, please check it out and do accept my pull request if you find it useful!!
Thank you :)

Added few more escape sequences

---

javascript.md

I added a section to the Javascript cheatsheet where I have explained the basics of destructuring with a few examples

Added 'Destructuring Arrays' section to Javascript cheatsheet

---

cpp.md
sql.md

A constraint was missing in sql.md which has been added

Updated a missing constraint in sql.md

---

sql.md

A constraint was missing which has been added in sql.md

Updated missing constraint in sql.md

---

c.md

Added math and random functions in C cheatsheet

---

typescript.md

Created typescript.md

---

search-engins.md

Updated data search-engins.md

---

c.md
sql.md

List within a list.
useful-when you want to create a matrix or want a list within list of different data types

Nestedlist

---

c.md
sql.md

Html entities used to print reserved characters.

Htmlentity

---

git.md

I have added a command to add upstream url to the local repo so that upstream changes can be pulled.  It resolves #472

Added `upstream` command

---

mongodb.md

Resubmitted shell help command

CristinaEU1

---

windows-shortcuts.md

It comprises of list of windows shortcut keys.

Created windows-shortcuts.md file

---

python.md

Generally beginners and even experienced programmers make the mistake of creating a new empty set as:
new_set = {}
but this will create a dictionary, therefore we should write:
new_set = set()

Added information about how to create a new set.

---

dart.md

Added syntax code for dart programming language

Added Dart language

---

javascript.md

I have added some of the Escape Sequences present in Java Script.
Please accept it.
Thank you!

Escape Sequences Added

---

javascript.md

I have added few more escape sequences into the already existing list.
Hope it helps!
Thank you :)

feat: added few more escape sequences

---

typescript.md

TypeScript Cheatsheets , we can make this a comprehensive resource for TypeScript developers.

TypeScript  cheatsheet

---

cd.md

Added a new trick for cd command which lets you switch to last working directory

Added a new trick for cd command

---

chmod.md

Added arguments related to chmod command

Add options for chmod

---

ada.md

Some parts inspired by the C++ cheatsheet.

Fix and improve Ada
